# Site settings
baseURL = "/"
languageCode = "en-us"
title = "MRF UP & UKZN 2018"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "MRF UP & UKZN 2018"
  description = "Responses to reconcilliation"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "MRF REGIONAL POD"
    subtitle = "By UP & UKZN"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"
      
    [[params.navigation.links]]
      name = "About"
      url = "about"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi there, we are Keenan, Thabo, Linet and Stuart"
    subtitle = "THIS WEBSITE CONTAINS A SERIES OF BLOGPOSTS DOCUMENTING OUR RESPONSES TO ISSUES OF RECONCILIATION RAISED AT THE MID-YEAR WORKSHOP."
    buttonText = "BLOGS"


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Keenan"
      subtitle = "Musician, UP"
      image = "keenan.jpg"
      url = "blogs/keenan"

    [[params.tiles.showcase]]
      title = "Thabo"
      subtitle = "Political scientist, UP"
      image = "thabo-full.jpg"
      url = "blogs/thabo"

    [[params.tiles.showcase]]
      title = "Linet"
      subtitle = "Environmental economist, UP"
      image = "linet1.jpg"
      url = "blogs/linet"

    [[params.tiles.showcase]]
      title = "Stuart"
      subtitle = "Grassland ecologist, UKZN"
      image = "stuart.jpg"
      url = "blogs/stuart"

    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "To the blogs"
    subtitle = """That's a quick overview of who we are. Follow the link below to check out our blogs."""
    buttonText = "BLOGS"
    url = "blogs"

  # Footer section
  [params.footer]
    enable = true
    copyright = "up&ukzn mrf regional pod"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://www.twitter.com"
      label = "Twitter"

    [[params.footer.social]]
      icon = "fa-facebook"
      url= "https://www.facebook.com"
      label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com"
      label = "Instagram"

