---
title: "Linet"
description: "There is a temptation to expect everyone to view reconciliation in the same way e.g. repatriations for past wrongs, or recognition of privilege or even just having conversations surrounding the need for reconciliation."
slug: "linet"
image: linet.jpg
keywords: ""
categories: 
    - ""
    - ""
date: 2019-09-02T22:26:09-05:00
draft: false
---

### 1.	What are you still learning and grappling with about yourself and how you tend to approach issues of reconciliation?

The ability to view reconciliation as a singular, subjective journey for all. There is a temptation to except everyone to view reconciliation in the same way e.g. repatriations for past wrongs, or recognition of privilege or even just having the same  conversations surrounding the need for reconciliation. Sometimes, we expect too much from people – to see what we see or think how we think. From the July workshop, I was confronted with the complexity of it all and was forced to recognise just how varied we are in viewing the ways in which issues of reconciliation must unfold. Consequently, I have been actively telling myself to embrace the ‘why’. Embracing people’s why is something that allows them to explain their internal progress, journeys and thoughts. Embracing the why allows me to pause and ask someone 'And why do you think so?', which almost always allows for much more communication and dialogue.

### 2.	Are there any fundamental beliefs you have about the world, about yourself, and about others that you’re afraid of having challenged? Why do you think this is the case?

I think for me, the most challenging and troubling beliefs that I hold are my Christian beliefs. Challenging in the sense that most of my peers and the world do not hold the same views. This sometimes makes it hard to relate to people, especially when my beliefs lead me to express myself in differing ways from the 'norm'. Troubling in the sense that what I may believe and ascribe to may sometimes strike others as enabling certain looked down upon or 'old fashioned' customs or thought patterns. I find that it is a balancing act and if I’m completely honest, I tend to have to adjust my tone and mannerisms depending on who I am relating to. Not that I am being inauthentic, but I have to watch what I say and how I express myself depending on who I am around. In the end, I am a person who loves to engage with a broad spectrum of people and I don’t mind facing these challenges. I know that we are connected in our humanity – our strengths, weaknesses and struggles. So, when I relate to people, I put their humanity and right to equality and dignity first, before I put myself and my views. 

Still, the way I live my life and what I hold as my fundamental personal, moral and religious views will probably not change (much), despite who I relate to and who challenges me. In fact, I welcome those challenges as a Christian and woman, as it helps me grow, seek and learn new things about my religion, culture, and the way I view myself and the people around me. So, to answer the question – I am not afraid to be challenged per say, I welcome the challenge as it helps me learn to ask myself tough questions and maybe even find answers to them. 

### 3.	What has shifted for you personally since the July workshop? Get specific. Maybe share stories of what’s changed.

After the night we were able to have the round circle and exercise in dialogue, I had an engaging discussion with my peers surrounding Christianity and relating to non-Christians. That discussion made me realise how little I knew about my religion apart from what has been fed to me throughout the years, in a somewhat dogmatic fashion. So, I embarked on a journey to read and find out more about the Bible, it’s strengths, weaknesses, and the challenges that may come with identifying as a Christian. I purchased a few interesting books that I am currently reading, such as The Gospel of Jesus, by John Davidson and Reaching for the Invisible God: What Can We Expect To Find? By Phillip Yancey.

### 4.	At the workshop you made some personal commitments regarding what you wanted to reconcile in your own life (“letting go, letting come”). How is that going? Where have you shifted and where do you feel “stuck?”

I cannot share much about this because it is such a sore spot for me. I am not getting anywhere with my resolutions. I feel stuck because I am still in the default mode of denial in terms of reconciling with my past and my family. I do not want to open pandora’s box because I am not sure what storm awaits me if I do. Also, I have so much to focus on right now - my academic work and the [TEDxUniversityofPretoria](https://www.ted.com/tedx/events/30405) event that I am organizing, so I really don’t have time to go down that path. I may be rationalizing my denial and refusal to address these topics, but it is what it is.

### 5.	Since the workshop, in your own environment (family, varsity, socially/with friends) where are you seeing new parts of yourself showing up as a leader or change agent? Share specific examples. What has influenced this change in you?

The most vivid and timely example I can give right now is my current experience as the Head Organizer of a TEDxUniversityofPretoria event scheduled to happen on the 19th of September at my campus. I have organized a [TEDx event](https://www.ted.com/tedx/events/23457) before at my previous university (UKZN) and it was a success. However, I was the only female in a group of five and it was a good experience for me test how I relate to the opposite sex in a high pressure, team setting. After the event, I became good friends with this group of males and I was sure that I related to them in a healthy, positive way and that they saw me as an equal. Approximately 8 months after the TEDxUKZN event, we happened to have a conversation as a group of 3 out of the 5 members, reminiscing of our time during the chaos of planning the event. In that conversation, the two guys I was with began to describe how they found me as “dominant” and “demanding” during the planning and that I was too “headstrong”. Upon hearing this news, I was firstly shocked because I thought that we had related in a perfectly equal dynamic and I had not had any inclination on their parts of such behavior from me. Secondly, I was extremely disappointed in myself because going into that exercise, I knew that I had a tendency of commanding a space and I was careful not to take over certain situations and be deferent to my team leader.

After the above conversation was had, I remember feeling downcast and questioning my own sense of leadership, my abilities as a leader and how I relate to people. Questions I asked myself were along the lines of: “Am I really that dominant?” “Do I always relate to people in such a way?” “Can I call myself a good leader if this is the experience people take away from me?” All these questions forced me to go through a reconciliatory journey with myself and with the friendships that I had made with my TEDx partners from UKZN. Primarily, I felt betrayed because I thought that they respected me, my presence and my personality. For them to use such words was triggering for me because I felt that they expected me to conform to conventional, stereotypical roles that females are usually expected to fill, especially in leadership positions and or while working with men. I also felt extremely disappointed in them, because I was under the impression that they were more progressive and open-minded men. Finally, I felt doubtful because at the time (April 2018), I had already put in an application to organize a TEDx event at UP and if it came back approved, I would then be the Head Organizer for that event. I was questioning whether I was up to that challenge and what my subsequent team members at UP would have to say about me.

A little while later, I had an enlightening conversation with a fellow MRF Scholar who, beyond reassuring me of my capacity, reminded me that in life, we cannot go about restraining ourselves in fear of what other people's perceptions of us are. He reassured me that most probably, their experiences of me were tainted by their societal and cultural expectations of women. He also reassured me that in no way did he find me dominating or over bearing. His words, coupled with a personal reminder of the success of our TEDxUKZN event made me realize that, whatever my methods of leadership were, they must have been sufficient as I was able to contribute to a memorable event. I was also able to consider how to better my leadership style through studying my enneagram and asking myself some critical questions - not to diminish my strengths in any way, but to translate them in a more palatable way to others. Finally, I reminded myself that change agents are those brave enough to speak up and mobilize forces and resources; there is no way one can do that without exhibiting some form of power and presence. 

I am still learning on this journey of leadership and I am consistently checking and rechecking myself and my actions. For TEDxUP, I am striving to be a good, democratic leader, who is able to delegate, while trusting in my team members (I have also been blessed with an amazing group of individuals as part of my organizing team). I am also consistently choosing to trust myself and my abilities. I know that above all, I relate with people on very human level because that’s what I like to do. In this way, I think that I can trust that bond to translate into a healthy working relationship in whatever setting I'm in, as long as I am mindful and self aware, as well as aware of others. 

